- Crew:
    agents:
    - Calculator
    name: calc crew
    tasks:
    - calculate
- Crew:
    agents:
    - Translator
    name: foo
    tasks:
    - translation task
- Crew:
    agents:
    - Prompt Engineer
    name: Prompt Engineer Crew
    tasks:
    - prompt task
- Crew:
    agents:
    - Research Analyst
    name: Smart Researcher
    tasks:
    - smart research task
- Crew:
    agents:
    - Research Reviewer
    name: Research Reviewer
    tasks:
    - Review Research Task
- Crew:
    agents:
    - Internet Researcher
    name: Excel Crew1
    tasks:
    - research digital infra
- Crew:
    agents:
    - EV Researcher
    name: EV Charger Locations
    tasks:
    - Research EV Chargers
- Crew:
    agents:
    - Report Summarizer
    - EV Researcher Checker
    name: EV Research Checks
    tasks:
    - summarize research
    - Check EV Charger Research
