- Task:
    agent: Prompt Engineer
    delegate: false
    description: 'Process this research prompt: {prompt}. If feedback is provided:
      {feedback}, incorporate it to improve the prompt. The revised prompt should
      be clear, focused, and ready for research execution.'
    expected_output: the revised prompt ready to be used as the description in a crewai
      task
    name: refine_prompt_task
    pydantic_class: self_eval_crew.EngineeredPrompt
    tools: []
- Task:
    agent: Digital Infra Researcher
    delgate: true
    description: "Research {industry} for which {company} has developed,\
      \ built or invested in within APAC, \nfor each investment identify precisely\
      \ all the parties who have co-invested and what the investment\nstructure is.\
      \  Identifying secondary investors by generic terms such as local investor is\
      \ not sufficient.  \nIf generic terms are used conduct secondary research cross\
      \ referencing the data centre location.\nWhen more that one data center exists\
      \ in a country identify the location in terms of city and suburb\n"
    expected_output: "a list of {industry} locations by subrub, city and country.\
      \  For each location, include power in {key metric} and\nwho are the shareholders in the\
      \ asset. The format of the output to be a well-organized table format using\
      \ JSON. \nIdentify the main entities, attributes and use them as keys in the\
      \ JSON object. Then, extract the relevant \ninformation from the text and populate\
      \ the corresponding values in the JSON object. \nEnsure that the data is accurately\
      \ represented and properly formatted within the JSON structure. \nThe resulting\
      \ JSON table should provide a clear, structured overview of the information\
      \ generated by the task \nin full.\n"
    name: research digital infra
    output_file: infra_research_task.txt
    tools:
    - Search Tavily
    - Search Internet
    - Search News
- Task:
    agent: Digital Researcher
    delgate: true
    description: 'For all of the secondary investors identfied in the previous tasks, research where

      other {industry} locations in APAC where that secondary investor has invested

      '
    expected_output: "{industry} locations by country.  For each location, include\
      \ power in MW and\nwho are the shareholders in the asset.  The format of the\
      \ output to be a well-organized table format using JSON. \nIdentify the main\
      \ entities, attributes and use them as keys in the JSON object. Then, extract\
      \ the relevant \ninformation from the text and populate the corresponding values\
      \ in the JSON object. \nEnsure that the data is accurately represented and properly\
      \ formatted within the JSON structure. \nThe resulting JSON table should provide\
      \ a clear, structured overview of the information generated by the task \nin\
      \ full.\n"
    name: secondary investor research
    output_file: infra_research_task.txt
    tools:
    - Search Internet
    - Search News
- Task:
    agent: Research Manager
    description: "monitor the tasks of the Digital Researcher and Web Site Reseacher\
      \ to ensure accuracy and that \nresults are delivered in a timely manner.\n"
    expected_output: accurate results including secondary investors described in specific
      terms in a timely fashion.
    name: monitor and manage research
    tools: null
- Task:
    agent: Report Summarizer
    delegate: true
    description: "consolidate output from previous tasks \r\n"
    expected_output: A summary of previous tasks in a well formed json format
    name: summarize research
    pydantic_class: ''
    tools: []
- Task:
    agent: News Researcher
    delgate: true
    description: 'Search local news sites in {country} for articles about data centre
      investments {language}

      '
    expected_output: 'a list of cities and suburbs where {industry} are being built
      or expanded

      '
    name: find investment announcements
    output_file: company_research_task.txt
    tools:
    - Search News
- Task:
    agent: News Researcher
    delegate: true
    description: "For the data centres, towns and secondary investors by the {industry}, search for 
      and in news articles between in {area}, {country}
      between {start_date} and {end_date}.Based on the news articles found
      work with the Internet Researcher for additional details, work with Fact Checker
      to ensure accuracy and relevance of research\n"
    expected_output: list of news articles with data centre location and investors
      as bullet points
    name: news research task
    output_file: news_research.txt
    tools:
    - Search News
    - Search Internet
- Task:
    agent: Corporate Researcher
    delgate: true
    description: 'For the secondary investors found by previous tasks,
      look for articles on their web sites which refer to {industry} deployments in {area},{country}

      between {start_date} and {end_date}, work with Fact Checker to ensure accuracy
      and relevance of research

      '
    expected_output: list of articles summarizing data centre, exact location and
      power in MW
    name: corporate research task
    output_file: company_research_task.txt
    tools:
    - Search Internet
    - Search Tavily
- Task:
    agent: Fact checker
    delegate: true
    description: "Fact check the information provided by Corporate Researcher\
      \ and Web Researcher to ensure relevance for {industry} in {region}\r\n"
    expected_output: relevant news articles summarised as a list
    name: fact checker
    pydantic_class: ''
    tools:
    - Search Tavily
    - Search Internet
- Task:
    agent: Web Site Researcher
    delegate: false
    description: "Using the list of web sites from the Digital Infra Structure Researcher's\
      \ tasks and\r\nanalyse the identified web pages and extract information about\
      \ amount of the investment and expected benefits.\r\nWhen available identify\
      \ the vendors and partners.\r\n"
    expected_output: bullet point list of investments
    name: web site trawl task
    tools:
    - Scrape Website
- Task:
    agent: Translator
    delegate: false
    description: "translate the output generated by the Senior Researcher, News Researcher,\
      \ Internet Researcher or Corporate Researcher to english for {language}\r\n\
      translate request made in english to {language} when Senior Researcher, News\
      \ Researcher, Internet Researcher or Corporate Researcher are searching articles\
      \ in {language}\r\n"
    expected_output: translated sentence
    name: translation task
    pydantic_class: self_eval_crew.ResearchResults
    tools: []
- Task:
    agent: Calculator
    delegate: false
    description: "calculat values based on the output from tasks"
    expected_output: 'a json with the result '
    name: calculate
    pydantic_class: ''
    tools: []
- Task:
    agent: Prompt Engineer
    delegate: false
    description: 'Process this research prompt: {prompt}. If feedback is provided:
      {feedback}, incorporate it to improve the prompt. The revised prompt should
      be clear, focused, and ready for research execution.'
    expected_output: the revised prompt ready to be used as the description in a crewai
      task
    name: prompt task
    pydantic_class: self_eval_crew.EngineeredPrompt
    tools: []
- Task:
    agent: Research Analyst
    delegate: true
    description: 'Research and analyze the following topic in detail: {prompt}'
    expected_output: A concise piece of research which is easily consumed by the CEO
      of an investment fund
    name: smart research task
    tools: []
- Task:
    agent: Research Analyst
    delegate: true
    description: 'Review: {research} and confirm if the total number of {metric} identified is with 10% to the total metric provided by the trusted source provided for {industry}.  If the variance is greater the research is not valid.  If the error is constistenly greater than 10% then flag this as an issue.  If not propose how to change the {research} result to be more granualar and matched against the detail of the trusted source.' 
    expected_output: Confirmation in the analysis is valid and feedback on why the
      analysis is complete or not
    name: Review Research Task
    pydantic_class: self_eval_crew.AnalysisReviewState
    tools:
    - Smart Excel RAG
    - Calculator
    - Search Internet
    
- Task:
    agent: EV Researcher Checker
    delegate: true
    description: List all regions and total ev charging points and calculate totals
    expected_output: Total number of EV points
    name: Check EV Charger Research
    pydantic_class: ''
    tools:
    - Smart Excel RAG
    - Calculator
